project:
  type: book

book:
  title: "Computational Social Science for Sustainability"
  subtitle: "11th International Conference on Computational Social Science in Norrk√∂ping, Sweden"
  author: "Matt Turner"
  date: "21 July 2025"
  chapters:
    - index.qmd
    - intro.qmd
    # - technical-intro.qmd
    # - writing.qmd
    - diffusion.qmd
    - cooperation.qmd
    - unfairness.qmd
    - opinion-change.qmd
    - references.qmd
  
bibliography: 
  - /Users/mt/workspace/Writing/library.bib
  - references.bib

format:
  html:
    toc: true
    include-in-header: header.html
    theme: 
      light:
        - theme-light.scss
        - styles.scss
      dark:
        - darkly 
        - theme-dark.scss
        - styles.scss
    fontsize: 0.9em
    linestretch: 1.2
  pdf:
    documentclass: scrreprt



